
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_OBJDICT_H
#define MASTER_OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_objdict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_objdict_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data master_objdict_Data;

#endif // MASTER_OBJDICT_H
