
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS16 WtStatus_1;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 WtSpd_1;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER32 WtPos_1;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 WtPosSpd_1;		/* Mapped at index 0x2003, subindex 0x00*/
extern INTEGER16 WtCurrent_1;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 RdStatus_1;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER16 RdSpd_1;		/* Mapped at index 0x2006, subindex 0x00*/
extern INTEGER32 RdPos_1;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 RdCurrent_1;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 RdAlarm_1;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 WtStatus_2;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 WtSpd_2;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER32 WtPos_2;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS16 WtPosSpd_2;		/* Mapped at index 0x200D, subindex 0x00*/
extern INTEGER16 WtCurrent_2;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 RdStatus_2;		/* Mapped at index 0x200F, subindex 0x00*/
extern INTEGER16 RdSpd_2;		/* Mapped at index 0x2010, subindex 0x00*/
extern INTEGER32 RdPos_2;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 RdCurrent_2;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS8 RdAlarm_2;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 WtStatus_3;		/* Mapped at index 0x2014, subindex 0x00*/
extern INTEGER16 WtSpd_3;		/* Mapped at index 0x2015, subindex 0x00*/
extern INTEGER32 WtPos_3;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 WtPosSpd_3;		/* Mapped at index 0x2017, subindex 0x00*/
extern INTEGER16 WtCurrent_3;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 RdStatus_3;		/* Mapped at index 0x2019, subindex 0x00*/
extern INTEGER16 RdSpd_3;		/* Mapped at index 0x201A, subindex 0x00*/
extern INTEGER32 RdPos_3;		/* Mapped at index 0x201B, subindex 0x00*/
extern UNS16 RdCurrent_3;		/* Mapped at index 0x201C, subindex 0x00*/
extern UNS8 RdAlarm_3;		/* Mapped at index 0x201D, subindex 0x00*/
extern UNS16 WtStatus_4;		/* Mapped at index 0x201E, subindex 0x00*/
extern INTEGER16 WtSpd_4;		/* Mapped at index 0x201F, subindex 0x00*/
extern INTEGER32 WtPos_4;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS16 WtPosSpd_4;		/* Mapped at index 0x2021, subindex 0x00*/
extern INTEGER16 WtCurrent_4;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS16 RdStatus_4;		/* Mapped at index 0x2023, subindex 0x00*/
extern INTEGER16 RdSpd_4;		/* Mapped at index 0x2024, subindex 0x00*/
extern INTEGER32 RdPos_4;		/* Mapped at index 0x2025, subindex 0x00*/
extern UNS16 RdCurrent_4;		/* Mapped at index 0x2026, subindex 0x00*/
extern UNS8 RdAlarm_4;		/* Mapped at index 0x2027, subindex 0x00*/
extern UNS16 WtFAcc_1;		/* Mapped at index 0x2028, subindex 0x00*/
extern UNS16 WtRAcc_1;		/* Mapped at index 0x2029, subindex 0x00*/
extern UNS16 WtF2RAcc_1;		/* Mapped at index 0x202A, subindex 0x00*/
extern UNS16 WtFAcc_2;		/* Mapped at index 0x202B, subindex 0x00*/
extern UNS16 WtRAcc_2;		/* Mapped at index 0x202C, subindex 0x00*/
extern UNS16 WtF2RAcc_2;		/* Mapped at index 0x202D, subindex 0x00*/
extern UNS16 WtFAcc_3;		/* Mapped at index 0x202E, subindex 0x00*/
extern UNS16 WtRAcc_3;		/* Mapped at index 0x202F, subindex 0x00*/
extern UNS16 WtF2RAcc_3;		/* Mapped at index 0x2030, subindex 0x00*/
extern UNS16 WtFAcc_4;		/* Mapped at index 0x2031, subindex 0x00*/
extern UNS16 WtRAcc_4;		/* Mapped at index 0x2032, subindex 0x00*/
extern UNS16 WtF2RAcc_4;		/* Mapped at index 0x2033, subindex 0x00*/

#endif // TESTMASTER_H
