
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Slave0x2000 = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
INTEGER32 Slave0x2001 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 Slave0x2002 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Slave0x2003 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 Slave0x2004 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 Slave0x2005 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS16 Slave0x2006 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER16 Slave0x2007 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
INTEGER32 Slave0x2008 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 Slave0x2009 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 Slave0x200A = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS16 Slave0x200B = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
UNS8 Slave0x200C = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS8 Slave0x200D = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS8 Slave0x200E = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS8 Slave0x200F = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS8 Slave0x2010 = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS8 Slave0x2011 = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 Slave0x2012 = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 1;

TIMER_HANDLE TestMaster_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x0;	/* 0 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestMaster_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestMaster_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestMaster_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 0;
                    UNS32 TestMaster_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestMaster_obj1017 = 0x00;	/* 0 */
                    subindex TestMaster_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TestMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TestMaster_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1201 :   Additional Server SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1201 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1201_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 0 */
                    UNS32 TestMaster_obj1201_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 0 */
                    UNS8 TestMaster_obj1201_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1201[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1201, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1201_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1201_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1201_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1202 :   Additional Server SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1202 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1202_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1202_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1202_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1202[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1202, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1202_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1202_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1202_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1203 :   Additional Server SDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1203 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1203_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1203_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1203_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1203[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1203, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1203_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1203_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1203_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1204 :   Additional Server SDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1204 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1204_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1204_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1204_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1204[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1204, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1204_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1204_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1204_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1205 :   Additional Server SDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1205 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1205_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1205_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1205_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1205[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1205, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1205_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1205_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1205_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1206 :   Additional Server SDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1206 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1206_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1206_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1206_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1206[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1206, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1206_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1206_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1206_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1207 :   Additional Server SDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1207 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1207_COB_ID_Client_to_Server_Receive_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1207_COB_ID_Server_to_Client_Transmit_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1207_Node_ID_of_the_SDO_Client = 0x0;	/* 0 */
                    subindex TestMaster_Index1207[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1207, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1207_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1207_COB_ID_Server_to_Client_Transmit_SDO, NULL },
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1207_Node_ID_of_the_SDO_Client, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 0 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 0 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 0 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1281_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1282_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1283_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1283, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1283_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1284_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1284, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1284_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1285_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1285, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1285_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1286_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex TestMaster_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1286, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1286_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x182;	/* 512 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0xff;	/* 0 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x64;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x64;	/* 0 */
                    UNS8 TestMaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 TestMaster_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x20060010,	/* 537264144 */
                      0x20070010,	/* 537329680 */
                      0x20080020,	/* 537395232 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1800_COB_ID_used_by_PDO = 0x202;	/* 384 */
                    UNS8 TestMaster_obj1800_Transmission_Type = 0xfe;	/* 0 */
                    UNS16 TestMaster_obj1800_Inhibit_Time = 0x64;	/* 0 */
                    UNS8 TestMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1800_Event_Timer = 0x3e8;	/* 0 */
                    UNS8 TestMaster_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 TestMaster_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 TestMaster_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 TestMaster_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestMaster_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A00[] = 
                    {
                      0x20000010,	/* 536870928 */
                      0x20010020,	/* 536936480 */
                      0x20020010,	/* 537002000 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A01[] = 
                    {
                      0x20030010,	/* 537067536 */
                      0x20040010,	/* 537133072 */
                      0x20050010,	/* 537198608 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03[7], NULL }
                     };

/* index 0x2000 :   Mapped variable Slave0x2000 */
                    subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2000, NULL }
                     };

/* index 0x2001 :   Mapped variable Slave0x2001 */
                    subindex TestMaster_Index2001[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Slave0x2001, NULL }
                     };

/* index 0x2002 :   Mapped variable Slave0x2002 */
                    subindex TestMaster_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2002, NULL }
                     };

/* index 0x2003 :   Mapped variable Slave0x2003 */
                    subindex TestMaster_Index2003[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2003, NULL }
                     };

/* index 0x2004 :   Mapped variable Slave0x2004 */
                    subindex TestMaster_Index2004[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2004, NULL }
                     };

/* index 0x2005 :   Mapped variable Slave0x2005 */
                    subindex TestMaster_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2005, NULL }
                     };

/* index 0x2006 :   Mapped variable Slave0x2006 */
                    subindex TestMaster_Index2006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2006, NULL }
                     };

/* index 0x2007 :   Mapped variable Slave0x2007 */
                    subindex TestMaster_Index2007[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Slave0x2007, NULL }
                     };

/* index 0x2008 :   Mapped variable Slave0x2008 */
                    subindex TestMaster_Index2008[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Slave0x2008, NULL }
                     };

/* index 0x2009 :   Mapped variable Slave0x2009 */
                    subindex TestMaster_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x2009, NULL }
                     };

/* index 0x200A :   Mapped variable Slave0x200A */
                    subindex TestMaster_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x200A, NULL }
                     };

/* index 0x200B :   Mapped variable Slave0x200B */
                    subindex TestMaster_Index200B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Slave0x200B, NULL }
                     };

/* index 0x200C :   Mapped variable Slave0x200C */
                    subindex TestMaster_Index200C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x200C, NULL }
                     };

/* index 0x200D :   Mapped variable Slave0x200D */
                    subindex TestMaster_Index200D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x200D, NULL }
                     };

/* index 0x200E :   Mapped variable Slave0x200E */
                    subindex TestMaster_Index200E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x200E, NULL }
                     };

/* index 0x200F :   Mapped variable Slave0x200F */
                    subindex TestMaster_Index200F[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x200F, NULL }
                     };

/* index 0x2010 :   Mapped variable Slave0x2010 */
                    subindex TestMaster_Index2010[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x2010, NULL }
                     };

/* index 0x2011 :   Mapped variable Slave0x2011 */
                    subindex TestMaster_Index2011[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x2011, NULL }
                     };

/* index 0x2012 :   Mapped variable Slave0x2012 */
                    subindex TestMaster_Index2012[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave0x2012, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1017,sizeof(TestMaster_Index1017)/sizeof(TestMaster_Index1017[0]), 0x1017},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1200,sizeof(TestMaster_Index1200)/sizeof(TestMaster_Index1200[0]), 0x1200},
  { (subindex*)TestMaster_Index1201,sizeof(TestMaster_Index1201)/sizeof(TestMaster_Index1201[0]), 0x1201},
  { (subindex*)TestMaster_Index1202,sizeof(TestMaster_Index1202)/sizeof(TestMaster_Index1202[0]), 0x1202},
  { (subindex*)TestMaster_Index1203,sizeof(TestMaster_Index1203)/sizeof(TestMaster_Index1203[0]), 0x1203},
  { (subindex*)TestMaster_Index1204,sizeof(TestMaster_Index1204)/sizeof(TestMaster_Index1204[0]), 0x1204},
  { (subindex*)TestMaster_Index1205,sizeof(TestMaster_Index1205)/sizeof(TestMaster_Index1205[0]), 0x1205},
  { (subindex*)TestMaster_Index1206,sizeof(TestMaster_Index1206)/sizeof(TestMaster_Index1206[0]), 0x1206},
  { (subindex*)TestMaster_Index1207,sizeof(TestMaster_Index1207)/sizeof(TestMaster_Index1207[0]), 0x1207},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},
  { (subindex*)TestMaster_Index1282,sizeof(TestMaster_Index1282)/sizeof(TestMaster_Index1282[0]), 0x1282},
  { (subindex*)TestMaster_Index1283,sizeof(TestMaster_Index1283)/sizeof(TestMaster_Index1283[0]), 0x1283},
  { (subindex*)TestMaster_Index1284,sizeof(TestMaster_Index1284)/sizeof(TestMaster_Index1284[0]), 0x1284},
  { (subindex*)TestMaster_Index1285,sizeof(TestMaster_Index1285)/sizeof(TestMaster_Index1285[0]), 0x1285},
  { (subindex*)TestMaster_Index1286,sizeof(TestMaster_Index1286)/sizeof(TestMaster_Index1286[0]), 0x1286},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},
  { (subindex*)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
  { (subindex*)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
  { (subindex*)TestMaster_Index1802,sizeof(TestMaster_Index1802)/sizeof(TestMaster_Index1802[0]), 0x1802},
  { (subindex*)TestMaster_Index1803,sizeof(TestMaster_Index1803)/sizeof(TestMaster_Index1803[0]), 0x1803},
  { (subindex*)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
  { (subindex*)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
  { (subindex*)TestMaster_Index1A02,sizeof(TestMaster_Index1A02)/sizeof(TestMaster_Index1A02[0]), 0x1A02},
  { (subindex*)TestMaster_Index1A03,sizeof(TestMaster_Index1A03)/sizeof(TestMaster_Index1A03[0]), 0x1A03},
  { (subindex*)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (subindex*)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (subindex*)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (subindex*)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (subindex*)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (subindex*)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (subindex*)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (subindex*)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
  { (subindex*)TestMaster_Index2008,sizeof(TestMaster_Index2008)/sizeof(TestMaster_Index2008[0]), 0x2008},
  { (subindex*)TestMaster_Index2009,sizeof(TestMaster_Index2009)/sizeof(TestMaster_Index2009[0]), 0x2009},
  { (subindex*)TestMaster_Index200A,sizeof(TestMaster_Index200A)/sizeof(TestMaster_Index200A[0]), 0x200A},
  { (subindex*)TestMaster_Index200B,sizeof(TestMaster_Index200B)/sizeof(TestMaster_Index200B[0]), 0x200B},
  { (subindex*)TestMaster_Index200C,sizeof(TestMaster_Index200C)/sizeof(TestMaster_Index200C[0]), 0x200C},
  { (subindex*)TestMaster_Index200D,sizeof(TestMaster_Index200D)/sizeof(TestMaster_Index200D[0]), 0x200D},
  { (subindex*)TestMaster_Index200E,sizeof(TestMaster_Index200E)/sizeof(TestMaster_Index200E[0]), 0x200E},
  { (subindex*)TestMaster_Index200F,sizeof(TestMaster_Index200F)/sizeof(TestMaster_Index200F[0]), 0x200F},
  { (subindex*)TestMaster_Index2010,sizeof(TestMaster_Index2010)/sizeof(TestMaster_Index2010[0]), 0x2010},
  { (subindex*)TestMaster_Index2011,sizeof(TestMaster_Index2011)/sizeof(TestMaster_Index2011[0]), 0x2011},
  { (subindex*)TestMaster_Index2012,sizeof(TestMaster_Index2012)/sizeof(TestMaster_Index2012[0]), 0x2012},
};

const indextable * TestMaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1201: i = 5;break;
		case 0x1202: i = 6;break;
		case 0x1203: i = 7;break;
		case 0x1204: i = 8;break;
		case 0x1205: i = 9;break;
		case 0x1206: i = 10;break;
		case 0x1207: i = 11;break;
		case 0x1280: i = 12;break;
		case 0x1281: i = 13;break;
		case 0x1282: i = 14;break;
		case 0x1283: i = 15;break;
		case 0x1284: i = 16;break;
		case 0x1285: i = 17;break;
		case 0x1286: i = 18;break;
		case 0x1400: i = 19;break;
		case 0x1401: i = 20;break;
		case 0x1402: i = 21;break;
		case 0x1403: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1601: i = 24;break;
		case 0x1602: i = 25;break;
		case 0x1603: i = 26;break;
		case 0x1800: i = 27;break;
		case 0x1801: i = 28;break;
		case 0x1802: i = 29;break;
		case 0x1803: i = 30;break;
		case 0x1A00: i = 31;break;
		case 0x1A01: i = 32;break;
		case 0x1A02: i = 33;break;
		case 0x1A03: i = 34;break;
		case 0x2000: i = 35;break;
		case 0x2001: i = 36;break;
		case 0x2002: i = 37;break;
		case 0x2003: i = 38;break;
		case 0x2004: i = 39;break;
		case 0x2005: i = 40;break;
		case 0x2006: i = 41;break;
		case 0x2007: i = 42;break;
		case 0x2008: i = 43;break;
		case 0x2009: i = 44;break;
		case 0x200A: i = 45;break;
		case 0x200B: i = 46;break;
		case 0x200C: i = 47;break;
		case 0x200D: i = 48;break;
		case 0x200E: i = 49;break;
		case 0x200F: i = 50;break;
		case 0x2010: i = 51;break;
		case 0x2011: i = 52;break;
		case 0x2012: i = 53;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  4, /* SDO_SVR */
  12, /* SDO_CLT */
  19, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  27, /* PDO_TRS */
  31 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  11, /* SDO_SVR */
  18, /* SDO_CLT */
  22, /* PDO_RCV */
  26, /* PDO_RCV_MAP */
  30, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

